language: ruby

os:
  - ubuntu
  - centos

gemfile:
  - testGemfile1
  - testGemfile2

script:
  - echo "script BUNDLE_GEMFILE = ${BUNDLE_GEMFILE}"

install:
  - echo "install BUNDLE_GEMFILE = ${BUNDLE_GEMFILE}"
