language: java

java-os:
  - centos
  - ubuntu
jdk:
  - openjdk8
  - openjdk9

script:
  - echo "script BUNDLE_GEMFILE = ${BUNDLE_GEMFILE}, SOME_VAR = ${SOME_VAR}"

install:
  - echo "install BUNDLE_GEMFILE = ${BUNDLE_GEMFILE}, SOME_VAR = ${SOME_VAR}"

